const jobs = [
  {
    color: 'red accent-4',
    id: 1,
    company: 'Reddit',
    location: 'San Francisco',
    salary: '$220,000',
    description: 'Bunch of nerds <3',
    title: 'Software Developer',
    postURL: 'indeed.com',
    subtitle: 'Do you wanna sub /r/life?',
    headquarters: 'NSFW',
    url: 'Reddit.com',
    year: '2004',
    type: 'Public',
    country: 'USA',
    notes: [],
    tasks: [],
    taskDate: null,
    deadline: null,
    applied: null,
    interview_1: null,
    interview_2: null,
    offer: null,
    status: 'WISHLIST'
  },
  {
    color: 'red accent-4',
    id: 2,
    company: 'Yelp',
    location: 'San Francisco',
    salary: '$300,000',
    description: 'Could found what are the best Tacos in the world? :O',
    title: 'Software Developer',
    postURL: 'indeed.com',
    subtitle: 'Bar hopping with confidence',
    headquarters: 'Hippie Land, CA',
    url: 'yelp.com',
    year: '2001',
    type: 'Public',
    country: 'USA',
    notes: [],
    tasks: [],
    taskDate: null,
    deadline: null,
    applied: null,
    interview_1: null,
    interview_2: null,
    offer: null,
    status: 'PHONE'
  },
  {
    color: 'pink accent-2',
    id: 3,
    company: 'Lyft',
    location: 'Austin',
    salary: '$122,000',
    description: 'Ride to hell?',
    title: 'Software Developer',
    postURL: 'indeed.com',
    subtitle: 'Lyft you up!',
    headquarters: 'Hippie Land, CA',
    url: 'lyft.com',
    year: '2012',
    type: 'Public',
    country: 'USA',
    notes: [],
    tasks: [],
    taskDate: null,
    deadline: null,
    applied: null,
    interview_1: null,
    interview_2: null,
    offer: null,
    status: 'APPLIED'
  },
  {
    color: 'orange accent-3',
    id: 5,
    company: 'Amazon',
    location: 'Seattle',
    salary: '$200,000',
    description: 'Free Prime?',
    title: 'Software Developer',
    postURL: 'indeed.com',
    subtitle: 'Priming to Retirement',
    headquarters: 'The Woods Seattle',
    url: 'Amazon.com',
    year: '1999',
    type: 'Public',
    country: 'USA',
    notes: [],
    tasks: [],
    taskDate: null,
    deadline: null,
    applied: null,
    interview_1: null,
    interview_2: null,
    offer: null,
    status: 'APPLIED'
  },
  {
    color: 'purple accent-2',
    id: 6,
    company: 'Medium',
    location: 'Ohio',
    salary: '$80,000',
    description: "Don't need a clap",
    title: 'Software Developer',
    postURL: 'indeed.com',
    subtitle: 'Medium to another world',
    headquarters: 'Austin',
    url: 'Medium.com',
    year: '2014',
    type: 'Private',
    country: 'USA',
    notes: [],
    tasks: [],
    taskDate: null,
    deadline: null,
    applied: null,
    interview_1: null,
    interview_2: null,
    offer: null,
    status: 'WISHLIST'
  },
  {
    color: '',
    id: 7,
    company: 'Chevron',
    location: 'Houston',
    salary: '$120,000',
    description: 'Pumping Code',
    title: 'Software Developer',
    postURL: 'indeed.com',
    subtitle: 'Unlimited Miles',
    headquarters: 'The Bayou',
    url: 'Amazon.com',
    year: '1920',
    type: 'Public',
    country: 'USA',
    notes: [],
    tasks: [],
    taskDate: null,
    deadline: null,
    applied: null,
    interview_1: null,
    interview_2: null,
    offer: null,
    status: 'PHONE'
  },
  {
    color: 'blue-grey darken-1',
    id: 8,
    company: 'United',
    location: 'Over the rainbow',
    salary: '$200,000',
    description: 'Unlimited Drags?',
    title: 'Software Developer',
    postURL: 'indeed.com',
    subtitle: 'Dragging you there since 1951',
    headquarters: 'Las Vegas',
    url: 'Amazon.com',
    year: '1999',
    type: 'Public',
    country: 'USA',
    notes: [],
    tasks: [],
    taskDate: null,
    deadline: null,
    applied: null,
    interview_1: null,
    interview_2: null,
    offer: null,
    status: 'ON SITE'
  },
  {
    color: 'teal accent-3',
    id: 9,
    company: 'Apple',
    location: 'Cupertino',
    salary: '180,000',
    description: "Wouldn't need an I.D with this face :D",
    title: 'Software Developer',
    postURL: 'indeed.com',
    subtitle: "Steve couldn't finish the job",
    headquarters: 'Cupertino',
    url: 'Apple.com',
    year: '1979',
    type: 'Public',
    country: 'USA',
    notes: [],
    tasks: [],
    taskDate: null,
    deadline: null,
    applied: null,
    interview_1: null,
    interview_2: null,
    offer: null,
    status: 'OFFER'
  },
  {
    color: 'cyan accent-2',
    id: 10,
    company: 'Equifax',
    location: 'New York',
    salary: '$200,000',
    description: 'Can you hide the hash?',
    title: 'Software Developer',
    postURL: 'indeed.com',
    subtitle: 'Sharing is caring',
    headquarters: 'New York',
    url: 'Equifax.com',
    year: '1969',
    type: 'Public',
    country: 'USA',
    notes: [],
    tasks: [],
    taskDate: null,
    deadline: null,
    applied: null,
    interview_1: null,
    interview_2: null,
    offer: null,
    status: 'REJECT'
  }
];

export default jobs;
